services:
  # Backend Python API
  - type: web
    name: edugen-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
    plan: free

  # Frontend React App  
  - type: web
    name: edugen-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://edugen-backend-isa4.onrender.com
      - key: VITE_GOOGLE_CLIENT_ID
        value: 417182243430-iio6ndabti96kaqr6eqh9golk6b2ev3i.apps.googleusercontent.com
      - key: VITE_TLDRAW_LICENSE_KEY
        value: "tldraw-2026-07-03/WyJwbEhLYW5qViIsWyIqIl0sMTYsIjIwMjYtMDctMDMiXQ.uvJat4iQ4Ut3OK5on038nDRcIQGy0G0n/78M4CfOFbGsvRKvCXsqTWc471MtLm06LqMxawsoofYbk/i0BRZYng"
    plan: free
